<html>
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
    </head>
    <body>
        <div id="content" class="content">
            <div class="title">
                <h3>Nhân Sự</h3>
            </div>
            <div class="clear"></div>
            <div class="table-content">
                <table id="user-table" class="user-table">
                    <th>ID</th>
                    <th>Nhân Viên</th>
                    <th>Email</th>
                    <th></th>
                    <th></th>
                    <tbody>
                        <?php foreach($this->a_users as $user): ?>
                            <td><?php echo $user['user_id'] ?></td>
                            <td><?php echo $user['username'] ?></td>
                            <td><?php echo $user['email'] ?></td>
                            <td><a href="#">Sửa</a></td>
                            <td><a href="#">Xóa</a></td>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>
 
