<?php
class Default_SearchController extends Zend_Controller_Action
{
    public function init()
    {
    }
    
    public function indexAction()
    {
        $doc = new Zend_Search_Lucene_Document();
        $doc->addField(Zend_Search_Lucene_Field::Keyword('doctype', 'autogenerated'));
        $doc->addField(Zend_Search_Lucene_Field::UnIndexed('created',time()));

//        echo $doc;
        die;
    }

    public function testAction()
    {
        print_r(glob(DEMO_DIR . '/Zend/Search/Lucene/indexing/IndexSource/*.html'));
        die;
    }

    public function createIndexAction()
    {
//        $index = Zend_Search_Lucene::create(
//                realpath(DATA_DIR . '/my-index'));
//        $doc = new Zend_Search_Lucene_Document();
//        $doc->addField(Zend_Search_Lucene_Field::Text('url', 'test_url'));
//        $doc->addField(Zend_Search_Lucene_Field::Text('contends', 'contests abc'));
//
//        $index->addDocument($doc);
//        echo 'Number of document: ';
//        echo $index->count();
//        echo PHP_EOL;
//        echo 'Done';
//        die;
    }

    public function retryIndexAction()
    {
        $index = Zend_Search_Lucene::open(
                realpath(DATA_DIR . '/my-index'));

        print_r($index);

        echo 'Number of document: ';
        echo $index->count();
        echo PHP_EOL;
        echo $index->numDocs();
        echo PHP_EOL;
        echo $index->maxDoc(); 
        die;
    }
}